### ISSUE TITLE
error Failed to set address

### ISSUE THREAD

**Issue by BJSingh** [alphacharlie/node-ads1x15#4]
I tried your library for raspberry pi and ads1115. But when run I get error failed to set address for line wire.setAddress(address); in i2c.coffee file. I have attach code file and error
code file: 
![codefile](https://cloud.githubusercontent.com/assets/5358553/17053074/dfc20742-501d-11e6-86ca-419602ec615f.PNG)

error file:
![errorfile](https://cloud.githubusercontent.com/assets/5358553/17053089/f3169e52-501d-11e6-8121-147bed604f6c.PNG)

**Comment by alphacharlie** [comment]
OK, This looks to be an **i2c** issue. A couple Questions - 
1. What hardware are you on? (i.e. which Raspberry pi board)
2. Is I2C enabled in raspi-config (and are the modules being loaded at boot?)
3. Does the file **/dev/i2c-1** (or **/dev/i2c-0** ) exist in your filesystem?

**Comment by BJSingh** [comment]
I am using Pi3. 
i2c was not enabled, I enabled then I got another error. 
/dev/i2c-1 is showing in file system after i2c enabled.
![error2](https://cloud.githubusercontent.com/assets/5358553/17076094/84075be2-50c6-11e6-92c6-4276dee54851.PNG)

**Comment by BJSingh** [comment]
Hello alphacharlie, issue has been resolved I am getting following output  when channel 0 connected to GND.
![output](https://cloud.githubusercontent.com/assets/5358553/17439122/17988606-5b44-11e6-8758-49fdd35d1a8a.PNG)

much close value, I will be testing more and will respond you about results.
Thanks,

**Comment by alphacharlie** [comment]
Glad you got it working! I'm now marking this one as closed. ;-)
