### ISSUE TITLE
I2C bus needs exposed.

### ISSUE THREAD

**Issue by nkolban** [alphacharlie/node-ads1x15#5]
I am trying to use node-ads1x15 on the CHIP (http://www.getchip.com) and CHIP has multiple I2C buses.  The one we want to use is /dev/i2c-2.  This issue requests the exposure of the parameter that defines the bus on which the device can be found.

**Comment by alphacharlie** [comment]
That's a good idea! So I implemented it. ;-) You should now be able to specify the i2c device as the third parameter of the node-ads1x15 module. Please test and let me know if you have any problems...

``` javascript
  var ads1x15 = require('node-ads1x15');  
  var chip = 0; //0 for ads1015, 1 for ads1115  

  var var adc = new ads1x15(chip, 0x48, 'dev/i2c-0');
```

et cetera, et cetera

Cheers,
Chuck
