### ISSUE TITLE
delay readADCSingleEnded too short

### ISSUE THREAD

**Issue by adwidianjaya** [alphacharlie/node-ads1x15#8]
I found strange behaviour of readADCSingleEnded, which produces random result sometimes. After I tried to increase the delay, about 10ms, random results didn't appear anymore. Could you please evaluate the formula which calculates the amount of delay for readADCSingleEnded function? Just curious, maybe it didn't produces proper value.

**Comment by michalvankodev** [comment]
I can see that the formula is just derived from the device specification but it seems like it's common that many converters are just not that fast how they should be. When I increased the delay I haven't seen bad results anymore.
